# Generated by Django 5.0.7 on 2026-06-14 06:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exchange_rate_to_group',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='expenseparticipant',
            name='share_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
